# Generated by Django 4.1 on 2023-07-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('amt_present', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('cc', 'cc'), ('hbl', 'hbl'), ('savings', 'savings'), ('joint', 'joint')], default='cc', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(choices=[('add', 'deposit'), ('substract', 'withdraw')], default='add', max_length=25)),
                ('is_cheque', models.BooleanField(default=False)),
                ('catalyst', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.account')),
            ],
        ),
    ]
