# Generated by Django 4.1 on 2023-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='pd_amt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='pd_upcoming_date',
            field=models.DateField(null=True),
        ),
    ]
