# Generated by Django 4.1 on 2023-07-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_flow_pd_amt_flow_pd_upcoming_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='pd_amt',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='pd_upcoming_date',
        ),
        migrations.AddField(
            model_name='account',
            name='pd_amt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pd_upcoming_date',
            field=models.DateField(null=True),
        ),
    ]
