# Generated by Django 4.1 on 2023-07-14 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_alter_account_pd_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], default='withdraw', max_length=25),
        ),
    ]
